# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/DevTools/Dev-Cpp/MinGW64/lib" -L"D:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2" -static-libgcc -L"D:/GitHub/Win32-API-Practice/ChildWindow" -mwindows -ldoublebuffer
INCS     = -I"D:/DevTools/Dev-Cpp/MinGW64/include" -I"D:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/GitHub/Win32-API-Practice/ChildWindow"
CXXINCS  = -I"D:/DevTools/Dev-Cpp/MinGW64/include" -I"D:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"D:/GitHub/Win32-API-Practice/ChildWindow"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
